language: scala
scala:
  - 2.12.8

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - .hydra
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
    - $HOME/.cache

script:
  - sbt ++$TRAVIS_SCALA_VERSION! clean validate
